name: Deploy Backend to Railway
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Railway
        uses: railwayapp/action@v1
        with:
          service: backend
          token: ${{ secrets.RAILWAY_TOKEN }}
          environment: production
